### ISSUE TITLE
Updating pypulseq

### ISSUE THREAD

**Issue by LeoMcBills** [josalggui/MaRGE#10]
I was thinking of updating **pypulseq** with [pypulseq](https://github.com/imr-framework/pypulseq/tree/dev/pypulseq) and so we can have sequences saved as **.seq** files instead of csv files.
What do you think @josalggui ?

**Comment by josalggui** [comment]
Hi!, last version of MaRGE is already compatible with pypulseq. But I still have a few sequences written in pypulseq, like RARE_pp and MSE_pp.
Now, a folder named 'seq' is craeated inside the session directory (that you can now open with a new button in the toolbars). Inside this folder you will find the seq file generated once the sequence is ready.

more info: https://github.com/josalggui/MaRGE/wiki/Create-your-own-sequence-PyPulseq-version

The interpreter still need to be manually installed, but I will update MaRGE with the interpreter already conatined. Also, you can find a PyPulseq template file in main/seq folder that should be able to guide you to make a pypulse sequence compatible with MaRGE. I will be updating on this line.

**Comment by LeoMcBills** [comment]
Oh thanks very much @josalggui, let me go check it out. otherwise I am therefore gonna close this issue.

**Comment by LeoMcBills** [comment]
Hello @josalggui, I hope that you are doing great today.
Kindly what did you mean by 
> The interpreter still need to be manually installed, but I will update MaRGE with the interpreter already conatined. Also, you can find a PyPulseq template file in main/seq folder that should be able to guide you to make a pypulse sequence compatible with MaRGE. I will be updating on this line.  

Otherwise I thought that the PSInterpreter already installed with MaRGE runs PyPulseq. I'm I wrong about this?

**Comment by josalggui** [comment]
Hi, the interpreter that I had already contained withing MaRGE was not fullly compatible with new versions of PyPulseq. At least I could not run new sequences that I wrote with pypulseq 1.4. I recommend to install the interpreter from https://github.com/catkira/flocra-pulseq/tree/pulseq_1.4 until I include this in the new release.

**Comment by LeoMcBills** [comment]
Oh thanks very much @josalggui otherwise I tried out the RARE_pp and the sequence ran successfully.
Thanks very much for the help.
