### ISSUE TITLE
Remove unnecessary experiment's module iimported in the main file and causing an error

### ISSUE THREAD

**Issue by LeoMcBills** [josalggui/MaRGE#11]
Hi @josalggui! While trying to set up MaRGE on another computer, I ran into an error showed below.
```bash
(gui) leo@mcbills:~/Desktop/MaRGE_Updated/MaRGE$ python3 main.py 
Traceback (most recent call last):
  File "/home/leo/Desktop/MaRGE_Updated/MaRGE/main.py", line 24, in <module>
    import experiment as ex
ModuleNotFoundError: No module named 'experiment'
```
I have cleared the line on which it is imported in main.py where it was not used anyway

**Comment by josalggui** [comment]
Hi @LeoMcBills, you're right, that line shouldn't be there. Also, if you're getting the error, it might be because the marcos_client folder isn't located at the same level as MaRGE.

**Comment by josalggui** [comment]
I deleted this from mine also, and will be updated in next version

**Comment by LeoMcBills** [comment]
Alright @josalggui, thanks very much.

I successfully set up MaRGE by correctly setting up the code structure.

Thanks very much 🙏🏿
